### PR TITLE
Update config.yaml

### PR DESCRIPTION
**Pull request by WolfgangWo**
## Config changes proposed in this pull request
- Add myself as a member

### I acknowledge that
- [x] I have **read and understood the [Open Source Guidelines](https://baloise.github.io/open-source/docs/arc42/)**
- [x] I agree to **act accordingly (with due dilligence) to our guidelines**
- [x] I have **no open questions** regarding the topics covered (please delete the "open questions" section)

### CODE REVIEW

**Comment by niiku** [comment]
@WolfgangWo Thanks for you PR. Please update the Commit in your PR so it matches your @baloise|basler email address. Currently, 28399559+WolfgangWo@users.noreply.github.com is being used (see here: https://patch-diff.githubusercontent.com/raw/baloise-incubator/org/pull/86.patch)

**Comment by WolfgangWo** [comment]
I've unchecked the "Keep my email address private" option in my profile. More than that, I don't see what I could do to the commit itself. Do you want to try again?

**Comment by niiku** [comment]
@WolfgangWo You need to replace the commit in the PR as the commit still contains the anonymized email address. So either force push to that branch or recreate the branch/pull request.

**Comment by WolfgangWo** [comment]
Closing this one.

**Pull request closed without merging**
