### PR TITLE
Update config.yaml

### PR DESCRIPTION
**Pull request by RiLi2001**
## Config changes proposed in this pull request
- 
- 

### I acknowledge that
- [x] I have **read and understood the [Open Source Guidelines](https://baloise.github.io/open-source/docs/arc42/)**
- [x] I agree to **act accordingly (with due dilligence) to our guidelines**
- [x] I have **no open questions** regarding the topics covered (please delete the "open questions" section)

### Open questions
- 
-

### CODE REVIEW

**Comment by joachimprinzbach** [comment]
@RiLi2001 tick the boxes pls, at least if you agree ;-)

**Comment by joachimprinzbach** [comment]
invalid emails: 1 of 1
97159276+rili2001@users.noreply.github.com

ERROR: NOT ALL EMAILS MATCH PATTERN ^[a-z.]+@(basler\.(ch|de)|baloise\.(be|ch|com|de|nl))$

**Comment by RiLi2001** [comment]
> invalid emails: 1 of 1 [97159276+rili2001@users.noreply.github.com](mailto:97159276+rili2001@users.noreply.github.com)
> 
> ERROR: NOT ALL EMAILS MATCH PATTERN ^[a-z.]+@(basler.(ch|de)|baloise.(be|ch|com|de|nl))$

Why is there an email error? Do I have to change something?

**Comment by RiLi2001** [comment]
> @RiLi2001 You propably have in the email settings activated that your email will be hidden for most actions. GitHub then replaces your real email with one with users.noreply.github.com
> 
> You can check on "Settings -> Email" under the option "Keep my email addresses private". If activated, then make sure the option is deactivated. Then the next time github will faciliate the pull request with your company email and the check will pass.

@janhkrueger  I deactivated it but the check is still unsuccessful :(

**Comment by janhkrueger** [comment]
The check will not be executed again on it's own.
When I had the same yesterday, the fastest for me was to close the old pull request and open a new one. With email adresses public and several (private and work) mail associated for my gitub account, I was able to select which mail to use when opening the pull request and then the check was successfull for me.
Might not be an elegant option, bit it did the job.

**Pull request closed without merging**
