### PR TITLE
Add chris-lipp and tommuelli

### PR DESCRIPTION
**Pull request by mikevader**
Members of the CaT Code Camp Team

## Config changes proposed in this pull request
- Add team members for the CaT code camp team
- 

### I acknowledge that
- [x] I have **read and understood the [Open Source Guidelines](https://baloise.github.io/open-source/docs/arc42/)**
- [x] I agree to **act accordingly (with due dilligence) to our guidelines**
- [x] I have **no open questions** regarding the topics covered (please delete the "open questions" section)

### Open questions
- 
-

### CODE REVIEW

**Comment by MarkusTiede** [comment]
Hi @mikevader - the idea is that each newly onboarded member files a PR on his / her own: and acknowledges the statements above (these are requirements of the cloud board). Does this makes sense?

**Review by MarkusTiede — CHANGES_REQUESTED** [review]
Please split in two separate PRs create by each new individual member.

**Comment by MarkusTiede** [comment]
At the moment we're gathering experience using this PR based approach - please feel free to add feedback here: https://github.com/baloise/open-source/issues/257

**Comment by mikevader** [comment]
I thought so after I saw the PR Template :)
But I said to my colleagues I would get it for them. But I will do it with them together in our next workshop.

@MarkusTiede can you tell me why the Travis CI has not reported back?

**Comment by christiansiegel** [comment]
Travis CI tries to dry-run apply the config change. This turns out to be quite unreliable. We'll remove that soon. For now the admins can overrule the failed CI when merging.

**Pull request closed without merging**
