### PR TITLE
added dombosfi to members

### PR DESCRIPTION
**Pull request by dombosfi**
## Config changes proposed in this pull request
- added dombosfi so he can access the Incubator for the DefectDojo Project

### I acknowledge that
- [x] I have **read and understood the [Open Source Guidelines](https://baloise.github.io/open-source/docs/arc42/)**
- [x] I agree to **act accordingly (with due dilligence) to our guidelines**
- [ ] I have **no open questions** regarding the topics covered (please delete the "open questions" section)

### Open questions
- Can I create my own namespace in which I can try to use my application?
- Can I concider this OpenShift cluster as a test environment with little to no chance of doing harm (beginner here)?

### CODE REVIEW

**Comment by christiansiegel** [comment]
Hi @dombosfi
As stated in our guidelines we require the Baloise eMail identity to be used: https://github.com/baloise-incubator/org/commit/9449ebc5cbb38b85e8c3d3c224dce5a0d2e5a6c4.patch please amend your commit with the correct author Identity.

**Review by MarkusTiede — CHANGES_REQUESTED** [review]
Hi @dombosfi - thanks for filing this and your questions: first of all could you please make sure to not use anonymous committer identity such as e.g. in your change provided: https://github.com/baloise-incubator/org/commit/9449ebc5cbb38b85e8c3d3c224dce5a0d2e5a6c4.patch

to answer your questions
- namespace are created in a gitops-manner: meaning ArgoCD manages the namespaces with the applications configured here: https://github.com/baloise-incubator/okd4-cluster-infra-apps
- test-env: yes the cluster & apps here is dev / playground only with a very low chance of breaking anything productive; though: I'd never say never :-)

**Comment by dombosfi** [comment]
If I understood correctly I need to use my baloise Email as my primary email? Additionally I'm not supposed to hide my primary email?

**Comment by MarkusTiede** [comment]
Exactly: you can easily e.g. amend this PR's commit.

**Comment by dombosfi** [comment]
I'm Sorry, I'm too ****** to do it. I will open a new pr. :(

**Comment by dombosfi** [comment]
Maybe you can show me how I can do it, for next time.

**Pull request closed without merging**
